require:
  - rubocop/rspec/focused
  - ./lib/unless_with_multiple_conditions
  - ./lib/private_attribute_accessors
  - ./lib/update_not_update_attributes

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'

BracesAroundHashParameters:
  Enabled: false

CaseIndentation:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Exclude:
    - "spec/**/*"

RescueModifier:
  Exclude:
    - "spec/**/*"

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/features/donations/metrics_spec.rb

Metrics/ModuleLength:
  Exclude:
    - spec/support/07_feature_helpers.rb

Style/PredicateName:
  Exclude:
    - "app/serializers/donation_form_serializer.rb"
    - "spec/models/concerns/version_helper_spec.rb"

Rails:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: 'flexible'

Rails/Date:
  EnforcedStyle: 'flexible'

Rails/Output:
  Exclude:
    - "lib/tasks/*"

RSpec/Focused:
  Enabled: true

Style/MethodName:
  Exclude:
    - spec/support/07_feature_helpers.rb

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/UnneededInterpolation:
  Exclude:
    - app/helpers/advanced_search_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Lint/UnusedMethodArgument:
  Exclude:
    - app/controllers/concerns/after_sign_in_path.rb

Rails/ApplicationRecord:
  Enabled: true

Style/GlobalVars:
  AllowedVariables:
    - $captured_feature_spec_headers
