require:
  - rubocop/rspec/focused
  - rubocop-thread_safety
  - rubocop-rails
  - ./lib/unless_with_multiple_conditions
  - ./lib/private_attribute_accessors
  - ./lib/update_not_update_attributes

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '*.gemspec'

Bundler/OrderedGems:
  Exclude:
    - "Gemfile"

Layout/CaseIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: False # disabled until autocorrectable in 0.87

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Date:
  EnforcedStyle: 'flexible'

Rails/Output:
  Exclude:
    - "lib/tasks/*"

Rails/TimeZone:
  EnforcedStyle: 'flexible'

RSpec/Focused:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - "spec/**/*"

Style/MethodDefParentheses:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - "spec/**/*"

Style/SignalException:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
