require:
  - rubocop-thread_safety
  - rubocop-rails
  - rubocop-rspec
  - ./lib/private_attribute_accessors
  - ./lib/update_not_update_attributes

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - '*.gemspec'

Bundler/OrderedGems:
  Exclude:
    - "Gemfile"

Layout/CaseIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: False # disabled until autocorrectable in 0.87

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_logical_operators

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Date:
  EnforcedStyle: 'flexible'

Rails/Output:
  Exclude:
    - "lib/tasks/*"

Rails/TimeZone:
  EnforcedStyle: 'flexible'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - "spec/**/*"

Style/SignalException:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Layout/ArgumentAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMemoization:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec:
  Enabled: false

RSpec/Focus:
  Enabled: true
